name: domestica
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.1.1
  cupertino_icons: ^1.0.8
  google_sign_in_android: ^6.1.31   # Update to the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # Update to the latest version
flutter:
  uses-material-design: true
  assets:
    - assets/kitchen.jpg
    - assets/window.jpg
    - assets/livingroom.jpg
    - assets/acservice.jpg
